# Generated by Django 5.1 on 2024-09-01 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0002_alter_processingrequest_csv_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processingrequest',
            name='csv_file',
            field=models.FileField(upload_to='processing/processed_csv/'),
        ),
    ]
